apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: react-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: react-app:1.0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 80
