apiVersion: apps/v1
kind: Deployment
metadata:
  name: hetzner-auction-ui
  namespace: hetzner-auction-ui
  labels:
    app: hetzner-auction-ui
spec:
  replicas: 2  # Run multiple replicas for high availability
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: hetzner-auction-ui
  template:
    metadata:
      labels:
        app: hetzner-auction-ui
    spec:
      containers:
      - name: hetzner-auction-ui
        image: hetzner-auction-ui:1.0.0
        imagePullPolicy: Never  # You might want to change this for production
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5