apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hetzner-auction-ui-pdb
  namespace: hetzner-auction-ui
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: hetzner-auction-ui
